# Generated by Django 5.2.7 on 2025-10-16 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplantas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='apellidos_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='calificacion',
            field=models.IntegerField(blank=True, help_text='Calificación de 1 a 5', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='centro_poblado',
            field=models.CharField(blank=True, help_text='Aldea, caserío, barrio, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentario_calificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentario_pago',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comentarios_internos',
            field=models.TextField(blank=True, help_text='Comentarios adicionales del equipo'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_compuesta',
            field=models.TextField(blank=True, help_text='Dirección completa formateada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='direccion_facturacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_deposito',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_viaje',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='link_pendientes',
            field=models.URLField(blank=True, help_text='Link a hoja de pendientes', max_length=500),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_deposito',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nit_facturacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombre_facturacion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pedido',
            name='nombres_cliente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pedido',
            name='numero_deposito',
            field=models.CharField(blank=True, help_text='No. de depósito bancario', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='orden_cerrada',
            field=models.BooleanField(default=False, help_text='¿La orden está completamente cerrada?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pendiente_viaje',
            field=models.BooleanField(default=True, help_text='¿Está pendiente de programar viaje?'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tecnico_encargado',
            field=models.ForeignKey(blank=True, help_text='Técnico asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_tecnico', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('contra_entrega', 'Pago Contra Entrega'), ('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_vendedor', to=settings.AUTH_USER_MODEL),
        ),
    ]
