# Generated by Django 5.2.7 on 2025-11-07 16:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webplantas', '0003_alter_pedido_fecha_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(help_text='Nombre de contacto', max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nit', models.CharField(blank=True, max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'transportista',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'ordering': ['placa']},
        ),
        migrations.AddField(
            model_name='pedidoruta',
            name='peso_estimado_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pedidoruta',
            name='prioridad',
            field=models.IntegerField(default=5, help_text='1=Alta, 5=Normal, 10=Baja'),
        ),
        migrations.AddField(
            model_name='pedidoruta',
            name='ventana_fin',
            field=models.TimeField(blank=True, help_text='Hora fin sugerida', null=True),
        ),
        migrations.AddField(
            model_name='pedidoruta',
            name='ventana_inicio',
            field=models.TimeField(blank=True, help_text='Hora inicio sugerida', null=True),
        ),
        migrations.AddField(
            model_name='pedidoruta',
            name='volumen_estimado_m3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='etiquetas',
            field=models.JSONField(blank=True, default=list, help_text='Lista de etiquetas aplicadas'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='km_estimados',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Kilómetros estimados de la ruta', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='operador_responsable',
            field=models.ForeignKey(blank=True, help_text='Operador que gestiona la ruta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutas_operadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='peso_total_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Peso total en kg', max_digits=10),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='ruta_plantilla',
            field=models.ForeignKey(blank=True, help_text='Ruta desde la cual se duplicó esta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='webplantas.rutaentrega'),
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='volumen_total_m3',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Volumen total en m³', max_digits=10),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='alto_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='ancho_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='capacidad_volumen_m3',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad en metros cúbicos', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='largo_m',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='observaciones',
            field=models.TextField(blank=True, help_text="Ej: 'No entra en terracería pesada'"),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='tipo',
            field=models.CharField(choices=[('camion', 'Camión'), ('pickup', 'Pickup'), ('panel', 'Panel')], default='camion', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedidoruta',
            name='foto_entrega',
            field=models.ImageField(blank=True, null=True, upload_to='entregas/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='pedidoruta',
            name='hora_llegada',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoruta',
            name='hora_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidoruta',
            name='orden_entrega',
            field=models.PositiveIntegerField(default=0, help_text='Orden en la ruta (parada)'),
        ),
        migrations.AlterField(
            model_name='rutaentrega',
            name='estado',
            field=models.CharField(choices=[('planificada', 'Planificada'), ('asignada', 'Asignada'), ('en_progreso', 'En Progreso'), ('en_transito', 'En Tránsito'), ('entregando', 'Entregando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('poliza', 'Póliza de Seguro'), ('rtv', 'Revisión Técnica Vehicular'), ('licencia', 'Licencia de Conducir'), ('otro', 'Otro')], max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_vehiculos/%Y/%m/')),
                ('observaciones', models.TextField(blank=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='webplantas.vehiculo')),
            ],
            options={
                'db_table': 'documento_vehiculo',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('aldea_colonia', models.CharField(blank=True, max_length=100)),
                ('direccion_completa', models.TextField()),
                ('referencia_ubicacion', models.TextField(help_text='Referencia corta de ubicación')),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webplantas.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webplantas.municipio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fincas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finca',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PuntoSiembra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('aldea_colonia', models.CharField(blank=True, max_length=100)),
                ('referencia_ubicacion', models.TextField(help_text='Referencia corta de ubicación')),
                ('activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webplantas.departamento')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webplantas.municipio')),
            ],
            options={
                'db_table': 'punto_siembra',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='rutaentrega',
            name='punto_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webplantas.puntosiembra'),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='transportista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='webplantas.transportista'),
        ),
    ]
